pushTime: 0 0/5 * * * ?
maxNum: 1
banWord:
  gs: 冒险助力礼包|纪行|预下载|脚本外挂|集中反馈|已开奖|云·原神|魔神任务|传说任务|线下赛|晋级赛|战绩更新|海选赛|邀请赛|积分赛|战绩工具|交流平台|首日赛|线上赛|社区内容|个人专访|全民赛|决赛|总决赛|半决赛|淘汰赛|作品展示|同人|大别野
  sr: 预下载|脚本外挂|集中反馈|已开奖|问题说明|意见反馈|账号封禁|工具|直播预告|获奖名单|大别野
  wd: 大别野|已开奖
  bb: 已开奖|大别野
  bbb: 封禁名单|大别野|马克兔速报|预下载
  zzz: 作品展示|已开奖|大别野
gsannounceGroup: {}
gsinfoGroup: {}
srannounceGroup: {}
srinfoGroup: {}
zzzannounceGroup: {}
zzzinfoGroup: {}
wdannounceGroup: {}
wdinfoGroup: {}
bbbannounceGroup: {}
bbbinfoGroup: {}
bbannounceGroup: {}
bbinfoGroup: {}
